#!/bin/bash

if test ! -z "$(cat /home/ark/.asoundrc | grep softvol)"
then
  awk -F'[][]' '/Left:/ { print $2 }' <(amixer sget Master)
elif test ! -z "$(cat /home/ark/.asoundrc | grep bluealsa)"
then
  pcm=$(bluealsa-cli list-pcms)
  bt_volval=$(bluealsa-cli volume ${pcm} | awk 'NR==1' | cut -d " " -f3)
  maxvolume=127
  echo "BT $(( 200 * $bt_volval/$maxvolume - 100 * $bt_volval/$maxvolume ))%"
  #echo "${bt_volvalpct}%"
else
  echo "N/A"
fi
