#!/usr/bin/env bash

printf "\033c" > /dev/tty0
dialog --clear

. /usr/local/bin/buttonmon.sh

Test_Button_X
if [ "$?" -eq "10" ]; then
  core="$(echo "$@" | grep -o -P '(?<=cores\/).*(?=_libretro.so)')"
  game="$(echo "$@" | grep -o -P '(?<=_libretro.so ).*(?=)')"
  emulator="retroarch"
  nonetplay=( "arduous" "atari800" "bluemsx" "coolcv" "dosbox" \
              "dosbox_pure" "duckstation" "easyrpg" "ecwolf" \
              "fake08" "flycast" "flycast32_rumble" "flycast_rumble" \
              "flycast_xtreme" "freechaf" "freeintv" "fuse" "gambatte" \
              "gpsp" "gw" "hatari" "mgba" "mgba_rumble" "mupen64plus" \
              "mupen64plus_next" "nekop2" "o2em" "onscripter" \
              "parallel_n64" "pcsx_rearmed" "pcsx_rearmed_rumble" \
              "pokemini" "ppsspp" "prosystem" "puae" "puae2021" \
              "px68k" "reicast_xtreme" "same_cdi" "scummvm" "swanstation" \
              "theodore" "uae4arm" "uzem" "vbam" "vba_next" "vecx" \
              "vemulator" "vice_x128" "vice_x64" "vice_xplus4" \
              "vice_xvic" "wasm4" "x1" )
  if [ ! -z $core ] && [[ ${nonetplay[@]} =~ $core ]]; then
    msgbox "The $core emulation core does not support netplay."
    exit 0
  fi
  netplay.sh "$core" "$game" "$emulator"
  results="$(echo $?)"

  if [ "$results" -eq "250" ]; then
    /opt/retroarch/bin/retroarch -c /home/ark/.config/retroarch/retroarch.cfg -H --nick=ArkOS_Host_"${core}"_Session_"$(cat /sys/class/net/wlan0/address | awk -F':' '{ print $4$5$6}')" "$@"
  elif [ "$results" -eq "138" ]; then
    /opt/retroarch/bin/retroarch -c /home/ark/.config/retroarch/retroarch.cfg --connect=192.168.1.1 --nick=ArkOS_Client_"${core}"_Session_"$(cat /sys/class/net/wlan0/address | awk -F':' '{ print $4$5$6}')" "$@"
  elif [ "$results" -eq "139" ]; then
    /opt/retroarch/bin/retroarch -c /home/ark/.config/retroarch/retroarch.cfg --connect=192.168.1.1 --nick=ArkOS_Spectator_"${core}"_Session_"$(cat /sys/class/net/wlan0/address | awk -F':' '{ print $4$5$6}')" --appendconfig=/home/ark/.config/retroarch/retroarch.cfg.spectate "$@"
  elif [ "$results" -eq "230" ]; then
    continue
  fi
  
  reset
  sudo setfont /usr/share/consolefonts/Lat7-Terminus20x10.psf.gz

  if [[ "$(iw dev wlan0 info | grep ssid | cut -c 7-30)" == *"ArkOS_"* ]] || [ -z "$(iw dev wlan0 info | grep ssid | cut -c 7-30)" ]; then
    arkos_ap_mode.sh Disable
  fi
  if [ "$results" -ne "230" ]; then
    exit 0
  fi
fi

if [ -f "/boot/rk3566.dtb" ] || [ -f "/boot/rk3566-OC.dtb" ]; then
  /usr/local/bin/controller_setup.sh

  if [ "$(ls /dev/input/ | wc -l)" -gt "7" ]; then
    testJoy=$(timeout 1 sdljoytest | grep Found)
    testJoy=$(echo "$testJoy" | cut -d " " -f6)
    if [ "$testJoy" -gt "1" ]; then
      /opt/retroarch/bin/retroarch -c /home/ark/.config/retroarch/retroarch.cfg --appendconfig=/home/ark/.config/retroarch/retroarch.cfg.ext "$@"
    else
      /opt/retroarch/bin/retroarch -c /home/ark/.config/retroarch/retroarch.cfg "$@"
    fi  
  else
    /opt/retroarch/bin/retroarch -c /home/ark/.config/retroarch/retroarch.cfg "$@"
  fi
else
  /opt/retroarch/bin/retroarch -c /home/ark/.config/retroarch/retroarch.cfg "$@"
fi
