#!/bin/bash

case $1 in
   pre)
    echo $(cat /sys/class/backlight/backlight/brightness) | sudo tee /var/local/cur_bright.state
    echo 0 | sudo tee /sys/class/backlight/backlight/brightness
    test=$(top -b -n 1 -d 0.2 -p $(pidof emulationstation) | tail -1 | awk '{print $9}')
    if (( ${test%.*} > 100 )); then
      systemctl stop emulationstation
    fi
    /usr/sbin/alsactl store -f /var/local/asound.state
    if [ -f "/usr/local/bin/quickmode.sh" ]; then
      touch /dev/shm/.JUSTWOKEUP
    fi
    sudo btconnected.sh check
    echo $(cat /home/ark/.config/.PowerLEDSleep) | sudo tee /sys/class/leds/Green\ LED/brightness
    echo 0 | sudo tee /sys/class/leds/Red\ LED/brightness
    sudo sleep_governors.sh SaveSettingsOnSleep
    ;;
   post)
    echo 0 | sudo tee /sys/class/leds/Green\ LED/brightness
    echo $(cat /var/local/cur_bright.state) | sudo tee /sys/class/backlight/backlight/brightness
    sudo sleep_governors.sh RestoreSettingsOnWake
    sudo /usr/sbin/alsactl restore -f /var/local/asound.state
    if [ ! -f "/dev/shm/QBMODE" ]; then
      systemctl is-active --quiet emulationstation.service && echo ok || systemctl start emulationstation
    fi
    sleep 2
    #sudo systemctl restart oga_events
    systemctl is-active --quiet enable_bluetooth.service && sudo systemctl restart enable_bluetooth
    systemctl is-active --quiet bluetooth.service && sudo systemctl restart bluetooth
    systemctl is-active --quiet bluealsa.service && sudo systemctl restart bluealsa
    systemctl is-active --quiet watchforbtaudio.service && sudo systemctl restart watchforbtaudio --no-block
    if [ -f "/var/local/btautoreconnect.state" ]; then
      sleep 15
      sudo btconnected.sh reconnect
      sudo rm -f /var/local/btautoreconnect.state
    fi
    systemctl is-active --quiet solarushotkey.service && sudo systemctl restart solarushotkey
    systemctl is-active --quiet pico8hotkey.service && sudo systemctl restart pico8hotkey
    systemctl is-active --quiet ppsspphotkey.service && sudo systemctl restart ppsspphotkey
    systemctl is-active --quiet openborhotkey.service && sudo systemctl restart openborhotkey
    systemctl is-active --quiet singehotkey.service && sudo systemctl restart singehotkey
    exit 0
    ;;
esac
