#!/bin/bash

##################################################################
# Created by Christian Haitian for use to display a message      #
# to the user.                                                   #
##################################################################

if [[ ! -e "/dev/input/by-path/platform-odroidgo2-joypad-event-joystick" ]]; then
  sudo setfont /usr/share/consolefonts/Lat7-TerminusBold28x14.psf.gz
fi

sudo chmod 666 /dev/tty1
export DIALOGRC=/opt/inttools/noshadows.dialogrc
printf "\033c" > /dev/tty1

if [[ -z $(pgrep -f gptokeyb) ]] && [[ -z $(pgrep -f oga_controls) ]]; then
  sudo chmod 666 /dev/uinput
  export SDL_GAMECONTROLLERCONFIG_FILE="/opt/inttools/gamecontrollerdb.txt"
  /opt/inttools/gptokeyb -1 "dialog" -c "/opt/inttools/keys.gptk" &
  set_gptokeyb="Y"
fi

# hide cursor
printf "\e[?25l" > /dev/tty1
dialog --clear

height="10"
width="20"

if test ! -z "$(cat /home/ark/.config/.DEVICE | grep RG503 | tr -d '\0')"
then
  height="15"
  width="60"
fi

if [ ${#1} -gt ${width} ]; then
  if [ ${#1} -gt "50" ]; then
    height="${#1}"
  fi
  width="${#1}"
fi

export TERM=linux
export XDG_RUNTIME_DIR=/run/user/$UID/

dialog --clear --msgbox "$1" $height $width 2>&1 > /dev/tty1

if [[ ! -z "$set_gptokeyb" ]]; then
  pgrep -f gptokeyb | sudo xargs kill -9
  unset SDL_GAMECONTROLLERCONFIG_FILE
fi

if [[ ! -e "/dev/input/by-path/platform-odroidgo2-joypad-event-joystick" ]]; then
  sudo setfont /usr/share/consolefonts/Lat7-TerminusBold20x10.psf.gz
fi

export DIALOGRC=
printf "\033c" > /dev/tty1
