#!/bin/bash

##################################################################
# Created by Christian Haitian for use to display a message      #
# to the user.                                                   #
##################################################################

if [[ ! -e "/dev/input/by-path/platform-odroidgo2-joypad-event-joystick" ]]; then
  if test ! -z "$(cat /home/ark/.config/.DEVICE | grep RGB20PRO | tr -d '\0')"
  then
    sudo setfont /usr/share/consolefonts/Lat7-TerminusBold32x16.psf.gz
  else
    sudo setfont /usr/share/consolefonts/Lat7-TerminusBold28x14.psf.gz
  fi
else
  sudo setfont /usr/share/consolefonts/Lat7-Terminus16.psf.gz
fi

sudo chmod 666 /dev/tty1
export DIALOGRC=/opt/inttools/noshadows.dialogrc
printf "\033c" > /dev/tty1

if [[ -z $(pgrep -f gptokeyb) ]] && [[ -z $(pgrep -f oga_controls) ]]; then
  sudo chmod 666 /dev/uinput
  export SDL_GAMECONTROLLERCONFIG_FILE="/opt/inttools/gamecontrollerdb.txt"
  /opt/inttools/gptokeyb -1 "dialog" -c "/opt/inttools/keys.gptk" > /dev/null &
  disown
  set_gptokeyb="Y"
fi

# hide cursor
printf "\e[?25l" > /dev/tty1
dialog --clear

height="10"
width="20"

if test ! -z "$(cat /home/ark/.config/.DEVICE | grep RG503 | tr -d '\0')"
then
  height="15"
  width="60"
fi

if [ ${#1} -gt ${width} ]; then
  if [ ${#1} -gt "200" ]; then
    height="${#1}"
  fi
  width="${#1}"
fi

export TERM=linux
export XDG_RUNTIME_DIR=/run/user/$UID/

# If a second argument (a dialog title) is given, we'll add it as output
if [ -n "$2" ]; then
  dialog --clear --title "$2" --msgbox "$1" $height $width 2>&1 > /dev/tty1
else
  # If no dialog title is given we'll just use the orignial line
  dialog --clear --msgbox "$1" $height $width 2>&1 > /dev/tty1
fi 

if [[ ! -z "$set_gptokeyb" ]]; then
  pgrep -f gptokeyb | sudo xargs kill -9
  unset SDL_GAMECONTROLLERCONFIG_FILE
fi

if [[ ! -e "/dev/input/by-path/platform-odroidgo2-joypad-event-joystick" ]]; then
  sudo setfont /usr/share/consolefonts/Lat7-Terminus20x10.psf.gz
fi

export DIALOGRC=
printf "\033c" > /dev/tty1
