#!/bin/bash

case $1 in
   pre)
    test=$(top -b -n 1 -d 0.2 -p $(pidof emulationstation) | tail -1 | awk '{print $9}')
    if (( ${test%.*} > 100 )); then
      systemctl stop emulationstation
    fi
    echo $(cat /sys/class/backlight/backlight/brightness) > /var/local/cur_bright.state
    echo 0 > /sys/class/backlight/backlight/brightness
    /usr/sbin/alsactl store -f /var/local/asound.state
    sudo btconnected.sh check
    ;;
   post)
    echo $(cat /var/local/cur_bright.state) > /sys/class/backlight/backlight/brightness
    /usr/sbin/alsactl restore -f /var/local/asound.state
    systemctl is-active --quiet emulationstation.service && echo ok || systemctl start emulationstation
    sleep 2
    sudo systemctl restart oga_events
    systemctl is-active --quiet enable_bluetooth.service && sudo systemctl restart enable_bluetooth
    systemctl is-active --quiet bluetooth.service && sudo systemctl restart bluetooth
    systemctl is-active --quiet bluealsa.service && sudo systemctl restart bluealsa
    systemctl is-active --quiet watchforbtaudio.service && sudo systemctl restart watchforbtaudio --no-block
    if [ -f "/var/local/btautoreconnect.state" ]; then
      sleep 15
      sudo btconnected.sh reconnect
      sudo rm -f /var/local/btautoreconnect.state
    fi
    systemctl is-active --quiet solarushotkey.service && sudo systemctl restart solarushotkey
    systemctl is-active --quiet pico8hotkey.service && sudo systemctl restart pico8hotkey
    systemctl is-active --quiet ppsspphotkey.service && sudo systemctl restart ppsspphotkey
    systemctl is-active --quiet openborhotkey.service && sudo systemctl restart openborhotkey
    systemctl is-active --quiet singehotkey.service && sudo systemctl restart singehotkey
    ;;
esac
